/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface User { 'createdAt' : Time, 'onboardingCompleted' : boolean }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'alternateSignup' : ActorMethod<
    [string, string],
    { 'message' : string, 'success' : boolean }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapRBAC' : ActorMethod<[], undefined>,
  'canAccessOnboarding' : ActorMethod<[], boolean>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  /**
   * / Lightweight update call that allows client to bring canister up to speed
   */
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRBACStatus' : ActorMethod<[], { 'bootstrapped' : boolean }>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRBACActive' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  /**
   * / Lightweight update call that allows client to bring canister up to speed
   */
  'warmup' : ActorMethod<[], { 'time' : Time, 'caller' : Principal }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];