/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const User = IDL.Record({
  'createdAt' : Time,
  'onboardingCompleted' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'alternateSignup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapRBAC' : IDL.Func([], [], []),
  'canAccessOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
  'completeOnboarding' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRBACStatus' : IDL.Func(
      [],
      [IDL.Record({ 'bootstrapped' : IDL.Bool })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRBACActive' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'warmup' : IDL.Func(
      [],
      [IDL.Record({ 'time' : Time, 'caller' : IDL.Principal })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const User = IDL.Record({
    'createdAt' : Time,
    'onboardingCompleted' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'alternateSignup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapRBAC' : IDL.Func([], [], []),
    'canAccessOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
    'completeOnboarding' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRBACStatus' : IDL.Func(
        [],
        [IDL.Record({ 'bootstrapped' : IDL.Bool })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRBACActive' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'warmup' : IDL.Func(
        [],
        [IDL.Record({ 'time' : Time, 'caller' : IDL.Principal })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };